### PR TITLE
Project Description

### PR DESCRIPTION
**Pull request by tanmaymohan**

### CODE REVIEW

**Comment by stevemann2705** [comment]
Remove Backend and Front End Categories and just include LinkedIn link for Contributors

**Comment by stevemann2705** [comment]
Include Flow Chart/Diagram explaining the working of project

**Review by stevemann2705 — CHANGES_REQUESTED** [review]
Remove FrontEnd and BackEnd Categories from Contributors list and use LinkedIn profile link for all

**Review by stevemann2705 — CHANGES_REQUESTED** [review]
Add flowchart/diagram for explaining the working of the project
-NO NEED for this as of now. Will be added later in the project

**Comment by tanmaymohan** [comment]
Can you elaborate more on the flowchart / diagram part ?

**Comment by stevemann2705** [comment]
try [draw.io](https://www.draw.io/)

**Review by stevemann2705 — APPROVED** [review]

**Pull request merged**
